### PR TITLE
GMT-like shaded relief illumination via `view.py --dem-blend`

### PR DESCRIPTION
**Pull request by yuankailiu**
**Description of proposed changes**

Hi @yunjunz,

Here is what MintPy has long been awaiting for :star2:!!! To be like GMT :satisfied:

Rather than plotting DEM in the background and overlaying the data with transparency, I attempt to view data with color adjusted by the shaded relief DEM when provided. Just like `gmt grdimage -I` feature. Hereafter, I call this way of showing data as "DEM-blended data".

This can be done via [`matplotlib.colors.LightSource.shade_rgb()` module](https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.LightSource.html#matplotlib.colors.LightSource.shade_rgb) (as opposed to what has been used in MintPy, i.e., the `LightSource.shade()` module, which only produces the shaded relief of the DEM itself).

Thus, I added two major functions in `plot.py` to handle this functionality of displaying DEM-blended data.

Changes in MintPy code are as follows.

+ `arg_utils.py`: allow the user to specify `--dem-blend`, `--shade-frac`, and `--base-color` arguments to activate and tune the DEM-blended data plotting.
  - `--dem-blend` : to activate the way of plotting the DEM-blended data
  - `--shade-frac` : tune the fraction or the contrast in shade_rgb()
  - `--base-color` : set the grayish color of the DEM background

+ `plot.py`:
   - `shaded_image()`: add illumination to the RGB data array based on a DEM file.
   - `shaded_colorbar()`: to plot a shaded illuminated colorbar. The shading is just schematic, not reflecting the real shades in the data (see future To-dos at the end of this PR).
   - `plot_image4view()`: handle the top layer plotting, this will call several other functions in plot.py, including the above two new functions.

+ `view.py`: adjust the current code to call new functions in plot.py. For a single plot, the DEM-blended data is shown well. We need to have some further tweaks for multiple subplots.

## Calling view.py examples:
```
# use a DEM from `inputs/srtm.dem` (you can also use your inputs/geometryGeo.h5) as shaded relief to adjust/blend the color of your velocity data, mask out pixels when data is NaN
view.py velocity.h5 velocity -c RdBu_r --dem inputs/srtm.dem --mask maskTempCoh.h5 --unit mm --ref-lalo 29.5463 36.0810 --vlim -4 4 --dem-nocontour --shade-exag 0.2 --dem-blend --base-color=0.9 --figtitle fancy-gmt-style
```
Results:
image

## Compare between the original view.py figure (left) and this PR (right). 

Shading parameters (shown in both figure titles) are intentionally adjusted so that the two plots have a similar color tone. The only difference is the style in which the DEM is displayed.

```
# left (original MintPy way of plotting data overlaying on top of the DEM)
view.py velocity.h5 velocity -c RdBu_r --dem inputs/srtm.dem --mask maskTempCoh.h5 --unit mm --ref-lalo 29.5463 36.0810 --vlim -4 4 --dem-nocontour --shade-exag 0.5 --shade-min -6000 --shade-max 3000 --alpha 0.8

# right (this PR; I set the default blend_mode in LightSource.shade_rgb() as 'hsv' for better visualization of the map)
view.py velocity.h5 velocity -c RdBu_r --dem inputs/srtm.dem --mask maskTempCoh.h5 --unit mm --ref-lalo 29.5463 36.0810 --vlim -4 4 --dem-nocontour --dem-blend --shade-exag 0.5 --shade-frac 0.3 --base-color=0.9

# They are using the same light source, with MintPy default --shade-az (315.) and --shade-alt (45.)
```

image

## Compare different `blend_mode`

There are three blend modes in `matplotlib.colors.LightSource.shade_rgb()`, {`hsv`,`overlay`,`soft`}. The default is `hsv`. Although matplotlib documentation says `overlay` or `soft` may be more realistic in showing elevation, `hsv` somehow looks better from my not-thoroughly tests (upper right panel in the below plot). 

image

However, `hsv` seems to have some artificial color jumps (upper right panel in the below plot) when plotting these Solid Earth tides apparent velocity with a tiny data range. 

image

## Future To-do

1. Know what was going on for `hsv` showing that color jump.

2. Implement this in the multiple subplots function, such as plotting all the geometries (height, longitude, latitude, incidencAngle, etc. with DEM shaded effects):
  ```
  view.py inputs/geometry.geo -d inputs/geometry.geo
  ```
  I try to adapt the code and implement this in plotting multiple subplots. But it still looks like it is plotting as the original MintPy way. The DEM-blended data does not seem to show up. 

3. The current fancy version of the colorbar with the illumination effects is not indicating the real shading in the data image. It is now serve only as a schematic. Although maybe it is hard to tell from our eyes. I did this by creating a fake color data from vmin & vmax in the colorbar axis, and adding yet another fake cosine-function elevation profile (hardcoded values) with shaded relief across the colorbar axis to micmic the illumination effects. Here, I have to use `soft` blend_mode for better performance. I know now it sounds pretty hacky, but it works. Check ([plot.py shaded_colorbar() function](https://github.com/insarlab/MintPy/compare/main...yuankailiu:MintPy:dev.view?expand=1#diff-d7ed74e02eb4fdfcb929a064ed7789be1de3838e47e8da6937bb42c8427abe64R2083)).

4. Perhaps some refactoring is needed.  

**Reminders**

- [x] Pass Pre-commit check (green)
- [x] Pass Codacy code review (green)
- [x] Pass Circle CI test (green)
- [x] Make sure that your code follows our style. Use the other functions/files as a basis.
- [x] If modifying functionality, describe changes to function behavior and arguments in a comment below the function declaration.
- [x] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by yunjunz** [comment]
> Know what was going on for `hsv` showing that color jump.

Yes, this is strange in the apparent solid Earth tides velocity. 

Testing on the FernandinaSenDT128 example dataset, I actually finds the `overlay` mode more appealing. Shall we add an option for it, and switch to `overlay` as default?

blend

**Comment by yuankailiu** [comment]
Ok, I think we can use `overlay` as default.

**Comment by yunjunz** [comment]
> Ok, overlay looks more realistic, hsv looks much more striking topography. I think we can use `overlay` as default and allow a `--blend-mode` input option.

Great, I am done with changes on my side for now.

**Comment by yuankailiu** [comment]
Thanks, I agree and will work on the suggestions above regarding functions inside utils.plot.

Yes, we can just allow for single plotting for now. Keep it simple. 

Yes, GMT does have a shaded color bar if your image is shaded with illumination. But I don't know what they do exactly.

**Comment by yuankailiu** [comment]
Hi @yunjunz, I am done with the changes.

**Review by yunjunz — APPROVED** [review]
All looks great to me now. Thank you @yuankailiu for this PR, I like the new style a lot: which has increased the contrast between the valid/invalid data, and removed the reliance on transparency, thus, resulting in a much prettier figure as well. 

I want to use this new style more after the PR and try it more intensively (to fine-tune the parameters), maybe we could switch to this style by default. Cheers!

Here is the comparison between the old and new style, for bookkeeping purposes, look how pretty it is!

+ Old style: hillshade + transparent data

```bash
view.py filt_220916-230217_5rlks_28alks_msk.int phase --dem 220916-230217_5rlks_28alks.hgt -c cmy
```

view_orig

+ New style: hillshade + DEM-blended data

```bash
view.py filt_220916-230217_5rlks_28alks_msk.int phase --dem 220916-230217_5rlks_28alks.hgt -c cmy --dem-blend
```

view_new

**Comment by hvasbath** [comment]
Awesome! This looks great!

**Comment by yuankailiu** [comment]
Hello Hannes, it's great to connect here! Of course

The major functions are:

[plot.prep_blend_image()](https://github.com/insarlab/MintPy/pull/1089/files#diff-d7ed74e02eb4fdfcb929a064ed7789be1de3838e47e8da6937bb42c8427abe64R2153): Prepare the RGBT array with an input DEM and an input data array. You can test those parameters and blend_modes to optimize the visualizations.
[plot.plot_blend_image()](https://github.com/insarlab/MintPy/pull/1089/files#diff-d7ed74e02eb4fdfcb929a064ed7789be1de3838e47e8da6937bb42c8427abe64R2221): Plot the RGBT array with pyplot.imshow()
[plot.blend_colorbar()](https://github.com/insarlab/MintPy/pull/1089/files#diff-d7ed74e02eb4fdfcb929a064ed7789be1de3838e47e8da6937bb42c8427abe64R2081): Plot the cool colorbar. This one right now is still a little hacky as you will see. `elev = np.ones_like(arr) * np.cos(0.6*x)`, I used an arbitrary cosine function as a fake elevation profile across the colorbar width to reflect the illumination effects. I don't know if it is the right way to do it, but it looks okay.

**Pull request merged**
