### PR TITLE
simple parallel plotting support in sbApp.py via joblib

### LINKED ISSUE #607: Plotting in parallel based on `mintpy.compute` information
@Ovec8hkin is so kind to implement this:

It would be great to implement plotting in parallel. For big mintpy runs the plotting takes longer than the calculations (the generation of 1 plot may take 1 minute, see below). There used to be a *bash script for parallel plotting but this capability got lost when a python script for plotting was introduced.

The plotting script should use the mintpy.compute informatiion as explained here:
insarlab/MintPy#531 (comment)

A relevant MintPy issue is:
insarlab/MintPy#538

```
-rw-rw---- 1 tg851601 G-820134 3627016826 Jul  9 09:45 S1_IW12_087_0527_0531_20141116_20210706.he5
-rw-rw---- 1 tg851601 G-820134    1028893 Jul  9 09:45 velocity.png
-rw-rw---- 1 tg851601 G-820134     613202 Jul  9 09:45 temporalCoherence.png
-rw-rw---- 1 tg851601 G-820134      55349 Jul  9 09:45 maskTempCoh.png
-rw-rw---- 1 tg851601 G-820134     133892 Jul  9 09:45 geometryRadar.png
-rw-rw---- 1 tg851601 G-820134     904417 Jul  9 09:46 unwrapPhase_wrap_1.png
-rw-rw---- 1 tg851601 G-820134     907636 Jul  9 09:47 unwrapPhase_wrap_2.png
-rw-rw---- 1 tg851601 G-820134     904043 Jul  9 09:47 unwrapPhase_wrap_3.png
-rw-rw---- 1 tg851601 G-820134     904362 Jul  9 09:48 unwrapPhase_wrap_4.png
-rw-rw---- 1 tg851601 G-820134     906580 Jul  9 09:49 unwrapPhase_wrap_5.png
-rw-rw---- 1 tg851601 G-820134     904527 Jul  9 09:49 unwrapPhase_wrap_6.png
-rw-rw---- 1 tg851601 G-820134     904285 Jul  9 09:50 unwrapPhase_wrap_7.png
-rw-rw---- 1 tg851601 G-820134     427987 Jul  9 09:50 unwrapPhase_wrap_8.png
-rw-rw---- 1 tg851601 G-820134     831011 Jul  9 09:51 unwrapPhase_1.png
-rw-rw---- 1 tg851601 G-820134     883294 Jul  9 09:51 unwrapPhase_2.png
-rw-rw---- 1 tg851601 G-820134     806346 Jul  9 09:52 unwrapPhase_3.png
-rw-rw---- 1 tg851601 G-820134     867724 Jul  9 09:53 unwrapPhase_4.png
-rw-rw---- 1 tg851601 G-820134     854075 Jul  9 09:53 unwrapPhase_5.png
-rw-rw---- 1 tg851601 G-820134     817647 Jul  9 09:54 unwrapPhase_6.png
-rw-rw---- 1 tg851601 G-820134     897264 Jul  9 09:55 unwrapPhase_7.png
-rw-rw---- 1 tg851601 G-820134     411140 Jul  9 09:55 unwrapPhase_8.png
-rw-rw---- 1 tg851601 G-820134     860438 Jul  9 09:56 coherence_1.png
-rw-rw---- 1 tg851601 G-820134     859624 Jul  9 09:56 coherence_2.png
-rw-rw---- 1 tg851601 G-820134     862093 Jul  9 09:57 coherence_3.png
-rw-rw---- 1 tg851601 G-820134     870757 Jul  9 09:57 coherence_4.png
-rw-rw---- 1 tg851601 G-820134     881368 Jul  9 09:58 coherence_5.png
-rw-rw---- 1 tg851601 G-820134     885124 Jul  9 09:58 coherence_6.png
-rw-rw---- 1 tg851601 G-820134     879605 Jul  9 09:59 coherence_7.png
-rw-rw---- 1 tg851601 G-820134     417247 Jul  9 09:59 coherence_8.png
-rw-rw---- 1 tg851601 G-820134     133606 Jul  9 10:00 connectComponent_1.png
-rw-rw---- 1 tg851601 G-820134     134989 Jul  9 10:02 connectComponent_2.png
-rw-rw---- 1 tg851601 G-820134     133267 Jul  9 10:03 connectComponent_3.png
-rw-rw---- 1 tg851601 G-820134     130772 Jul  9 10:04 connectComponent_4.png
-rw-rw---- 1 tg851601 G-820134     125092 Jul  9 10:05 connectComponent_5.png

```

### PR DESCRIPTION
**Pull request by Ovec8hkin**
Added support for plotting MintPy figures in parallel in `smallbaselineApp.py`. Previous iterations did this using a bash script, but this is now implemented in pure python (#538) through the use of the `joblib` library. Parallel resources can be configured and set through modification of the `mintpy.compute` options in `smallbaselineApp.cfg`.

**Reminders**

- [x] Fix #607
- [x] Pass Codacy code review (green)
- [x] Pass Circle CI test (green)
- [x] Make sure that your code follows our style. Use the other functions/files as a basis.
- [x] If modifying functionality, describe changes to function behavior and arguments in a comment below the function declaration.
- [x] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Review by yunjunz — APPROVED** [review]
Thank you @Ovec8hkin for bringing this back!

From my local testing with the default of 4 parallel workers, the total run time got cut in half.

**Comment by Ovec8hkin** [comment]
Some testing on stampede with a larger dataset and 17 cores brought processing time from ~3.5 minutes to ~45 seconds.

I didn't do any stringent memory testing, but I don't know how critical that is for you.

**Comment by yunjunz** [comment]
I tested it on a dataset with ifgramStack.h5 in size of 2000 by 1700 by 98, one call of view.py uses <500 MB of memory. With the default setups, it would sum up to 2GB, less than the 4GB default. Thus, without further modifying code for memory here is fine with me.

**Comment by falkamelung** [comment]
Thank you @Ovec8hkin !
For a big dataset the plotting now takes 7 minutes compare to 20 minutes previously. As always on HPC, the saved time is another 30% more because we can specify a smaller walltime.

**Pull request merged**
