### PR TITLE
Updated mask.py to work with coherence files and others

### PR DESCRIPTION
**Pull request by rzinke**
**Description of proposed changes**

https://github.com/insarlab/MintPy/issues/475

**Reminders**

- [ ] Pass Codacy code review (green)
- [ ] Pass Circle CI test (green)
- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] If modifying functionality, describe changes to function behavior and arguments in a comment below the function declaration.

### CODE REVIEW

**Review by yunjunz — CHANGES_REQUESTED** [review]
Could you base your `maskFix` branch against the latest `insarlab/main`? The error in the circle ci test is caused by installing/using the latest h5py v3+. It has been fixed by constraining h5py<3.

**Comment by yunjunz** [comment]
There is a link on `git rebase` here: https://github.com/insarlab/MintPy/blob/main/docs/CONTRIBUTING.md#divergence-between-upstreammain-and-your-feature-branch.

I understand it's AGU season, if you don't have time to learn git rebase, let me know. I could run the testing locally on my laptop.

**Comment by rzinke** [comment]
> There is a link on `git rebase` here: https://github.com/insarlab/MintPy/blob/main/docs/CONTRIBUTING.md#divergence-between-upstreammain-and-your-feature-branch.
> 
> I understand it's AGU season, if you don't have time to learn git rebase, let me know. I could run the testing locally on my laptop.

Ah. This sounds quite useful. I'd much appreciate if you could run locally, though! 
Many thanks,
Rob

**Review by yunjunz — APPROVED** [review]
Passed the tests locally. The error from the circle ci test is not related to the changes in this PR. 

Thank you @rzinke!

**Pull request merged**
