### PR TITLE
add code to convert lv_theta to incidence angle and update the dir_structure.md

### PR DESCRIPTION
**Pull request by cirrusasf**
**Description of proposed changes**

**Reminders**

- [ ] Fix #xxxx
- [ ] Pass Codacy code review (green)
- [ ] Pass Circle CI test (green)
- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] If modifying functionality, describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Review by yunjunz — CHANGES_REQUESTED** [review]
Hi @cirrusasf, there are too many unrelated commits in this PR. Please either `git rebase` to the latest version of the `main` branch, OR re-fork `insarlab/MintPy` and then add your changes.

**Comment by yunjunz** [comment]
1. Could you send me a copy of the Ridgecrest dataset if we plan to use it as a reference in the documentation? From this PR, I see two pairs only. It will be good to have a longer and redundant network, e.g. 30 pairs from 10 acquisitions.

This will help me to test the functionality and for long-term maintenance. If you would like, we could also work together to upload an example dataset to Zenodo as I did for other processors.

2. mintpy only needs one copy of geometry datasets (angles, height, masks, etc.) for one stack, thus, ASF might want to implement this feature instead of creating one copy for every interferogram to save computing and disk.

**Comment by cirrusasf** [comment]
Hi Yunjun,

1. We definitely want to upload the example dataset somewhere. The
example dataset will be accessible after we put them on the aws s3. I will
let you know.

2. We can refine our notebook to just include the files that mintPy needs.

Jiang

**Comment by yunjunz** [comment]
I think I have covered the changes here in #640. If you think there are more changes needed, please rebase or issue a new PR. Cheers.

**Comment by cirrusasf** [comment]
Thank you for merge the PR.

**Pull request closed without merging**
