### PR TITLE
Initial Docker image with config file

### PR DESCRIPTION
**Pull request by andretheronsa**
Added instructions to run the Docker container from Dockerhub to Installation.md

Also added a root level docker directory for the dockerfile. Please review whether this is the right place, or even necessary. In this way anyone can inspect or modify the dockerfile and build their own container instead of using the prebuilt one on dockerhub.

### CODE REVIEW

**Comment by yunjunz** [comment]
I moved the instruction of running docker to docker/README.md, following isce2 structure.

**Comment by yunjunz** [comment]
Thank you for the commit @andretheronsa!

`Codacy` is suggesting to use `SHELL ["/bin/bash", "-c"]` to replace `RUN ln -sfv /bin/bash /bin/sh` to change the default shell, could you test if this works?

https://app.codacy.com/app/insarlab/MintPy/pullRequest?prid=3868908

**Comment by andretheronsa** [comment]
@yunjunz I don't expect that to work. I believe SHELL only changes the default shell during the docker build time for commands you want to RUN in the dockerfile.
We need to change the shell 'permanently' in the actual container to ensure the .sh scripts get invoked correctly.

**Comment by yunjunz** [comment]
@andretheronsa Thank you for the clarification.

**Pull request merged**
