### PR TITLE
spatial_filter: refactor double difference

### PR DESCRIPTION
**Pull request by forrestfwilliams**
- combine the local and regional filter into
  one filter to reduce number of
  convolutional operations

- change regional filter shape from a disk to
  a doughnut

**Reminders**

- [x] Fix #xxxx
- [x] Pass Codacy code review (green)
- [x] Pass Circle CI test (green)
- [x] Make sure that your code follows our style. Use the other functions/files as a basis.
- [x] If modifying functionality, describe changes to function behavior and arguments in a comment below the function declaration.
- [x] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by yunjunz** [comment]
Thank you @forrestfwilliams. Applying one convolution sounds like a good idea. I am wondering what's the motivation for changing the shape of the regional filter from a disk to a donut?

**Comment by forrestfwilliams** [comment]
Hey @yunjunz, good question! The small `local_kernel` is meant to represent the local deformation signal, while the `regional_kernel` is supposed to represent the deformation occurring outside of the local area. By not including `local_kernel` pixels within the `regional_kernel` (i.e. making the regional kernel a doughnut) we are trying to capture only the regional signal in the `regional_kernel`.

In practice, @dbekaert found that the `regional_kernel` is typically large enough that the effect of including the `local_kernel` pixels is negligible, but I thought it would be good to make this modification regardless. Especially since it does not require any extra steps when you're already combining the two kernels.

**Comment by yunjunz** [comment]
Thank you for the explanation @forrestfwilliams, that makes sense. Could you please add this as comments next to the code as well? I believe that would help other users too.

**Comment by forrestfwilliams** [comment]
Can do!

**Review by yunjunz — APPROVED** [review]
Looks great. Thank you @forrestfwilliams.

**Comment by forrestfwilliams** [comment]
Thank you @yunjunz !

**Pull request merged**
