### PR TITLE
smallbaselineApp: get ionStack file & add metadata from custom template file

### PR DESCRIPTION
**Pull request by yuankailiu**
**Description of proposed changes**

+ now the MintPy custom metadata from your template will be added to the ionStack while:

e.g., `smallbaselineApp.py AqabaSenAT087.cfg --dostep load_data`

This action was already be applied to `ifgramStack.h5` and `geometry*.h5`.

**Reminders**

- [x] Pass Codacy code review (green)
- [x] Pass Circle CI test (green)
- [x] Make sure that your code follows our style. Use the other functions/files as a basis.
- [x] If modifying functionality, describe changes to function behavior and arguments in a comment below the function declaration.
- [x] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by yuankailiu** [comment]
Alright, I need to find out why there is an error in geocode step. But I did not change that part of the code.
```
******************** step - geocode ********************
Traceback (most recent call last):
  File "/root/tools/miniconda3/bin/smallbaselineApp.py", line 8, in <module>
    sys.exit(main())
  File "/root/tools/miniconda3/lib/python3.9/site-packages/mintpy/smallbaselineApp.py", line 1281, in main
    app.run(steps=inps.runSteps)
  File "/root/tools/miniconda3/lib/python3.9/site-packages/mintpy/smallbaselineApp.py", line 1088, in run
    self.run_geocode(sname)
  File "/root/tools/miniconda3/lib/python3.9/site-packages/mintpy/smallbaselineApp.py", line 941, in run_geocode
    print('\ngeocode.py', ' '.join(iargs))
TypeError: sequence item 6: expected str instance, NoneType found
Traceback (most recent call last):
  File "/root/tools/MintPy/tests/smallbaselineApp.py", line 207, in <module>
    main(sys.argv[1:])
  File "/root/tools/MintPy/tests/smallbaselineApp.py", line 184, in main
    test_smallbaselineApp(dset_name,
  File "/root/tools/MintPy/tests/smallbaselineApp.py", line 151, in test_smallbaselineApp
    raise RuntimeError('Test failed for example dataset {}'.format(dset_name))
RuntimeError: Test failed for example dataset FernandinaSenDT128
```

**Comment by yunjunz** [comment]
Hi @yuankailiu, I like the changes of adding ionStack.h5 to smallbaselineApp.py.

For the specific purpose of adding custom metadata, I would think they are added already inside `load_data.py` [here](https://github.com/insarlab/MintPy/blob/719c2b4ad2457bbbef01d2b0842d3804e6e9203d/mintpy/load_data.py#L866) and [here](https://github.com/insarlab/MintPy/blob/719c2b4ad2457bbbef01d2b0842d3804e6e9203d/mintpy/load_data.py#L971), which will only add those in MACRO_CASE, isn't it?

I like it in load_data.py better than smallbaselineApp.py, and would plan to remove the one from smallbaselineApp.py in the future.

**Review by yunjunz — APPROVED** [review]
LGTM. Thank you @yuankailiu.

**Comment by yuankailiu** [comment]
@yunjunz , I did not notice you help me to fix the bug. Thanks a lot!

**Pull request merged**
