### PR TITLE
load ionosphere stack from isce2/topsStack

### PR DESCRIPTION
**Pull request by yuankailiu**
In these updates, the attempt is to load the ionosphere datasets from topsStack processor into MintPy as an independent `ionoStack.h5`. Thus, it can be inverted separately to a time series for ionosphere correction in the time-series domain.

+ load ionosphere files (phase, coherence) from topsStack
+ create an independent ionoStack.h5 for iono datasets
+ handle xstep/10, ystep/10 for ionoStack.h5 (topStack iono was further multilook)
+ add an option to allow load_data.py to load only the geometry files
+ when creating stack file, fill nan for missing pairs (remove it)
+ add identidyable datasetName 'ionoPhase', 'ionoCoherence' in several codes (just be consistent with ifgramStack)
+ trailing whitespaces removed in several places

New functionalities in `load_data.py`:
`load_data.py --help`
```
  --geom                Only write the geometry files
  --ionostack           Switch to load the ionospheric pairs into an independent stack
                        (define paths in the template file)
```

The general workflow with ionospheric correction could be:

```bash
cd ${mintpy_work_dir}/

# 1. Regular time series analysis w/o iono correction, until network inversion
smallbaselineApp.py ${config} --dostep invert_network

# 2.1 Load the iono stack separately
load_data.py -t ${config} --project AqabaSenAT087 --ionostack

# 2.2 Remember to reference the ionoStack
reference_point.py inputs/ionoStack.h5 -t ${config}

# 2.3 We can plot the iono network (change four file names)
cd inputs && plot_network.py ionoStack.h5 -d ionoCoherence -t ${config} --nodisplay --cmap-vlist 0.2 0.7 1.0

# 2.4 Invert the ionoStack separately with no weighting, move the files if you want (lets' change to iono.h5 saved in inputs/)
ifgram_inversion.py inputs/ionoStack.h5 -i ionoPhase -m waterMask.h5 -w no --update && mv *ion.h5 inputs/

# 3. Phase corrections: since the iono correction is not integrated into the smallbaselineApp.py yet,
# one needs to run the stand-alone scripts for each correction.
diff.py timeseries.h5 inputs/ion.h5 -o timeseries_ion.h5
tropo_pyaps3.py timeseries_ion.h5 -g inputs/geometryRadar.h5 -o timeseries_ion_ERA5.h5
...
```

You will need to have a template configuration file containing the following:
```
##---------interferogram datasets:
mintpy.load.unwFile        = ../submit_arrays/merged/interferograms/*_*/filt_fine.unw  #[path pattern of unwrapped interferogram files]
mintpy.load.corFile        = ../submit_arrays/merged/interferograms/*_*/filt_fine.cor  #[path pattern of spatial coherence       files]
mintpy.load.connCompFile   = ../submit_arrays/merged/interferograms/*_*/filt_fine.unw.conncomp  #[path pattern of connected components    files], optional but recommended
mintpy.load.intFile        = ../submit_arrays/merged/interferograms/*_*/filt_fine.int  #[path pattern of wrapped interferogram   files], optional
mintpy.load.ionoFile       = ../submit_arrays/ion/*_*/ion_cal/filt.ion                 #[path pattern of ionospheric delay       files], optional
mintpy.load.ionocorFile    = ../submit_arrays/ion/*_*/ion_cal/raw_no_projection.cor    #[path pattern of ionospheric coherence   files], optional !!!THIS IS THE NEW STUFF!!!
```

We better set downsampling here, so it downsample the regular InSAR files 10 times:
```
##---------multilook (optional):
## multilook while loading data with nearest interpolation, to reduce dataset size
mintpy.load.ystep          = 10    #[int >= 1], auto for 1 - no multilooking
mintpy.load.xstep          = 10    #[int >= 1], auto for 1 - no multilooking
```

Since topStack generated iono files are already 10 times less in size, in my code it will divide this {xstep, ystep} by 10 (10/10=1, thus no further down sampling for the iono) to handle that factor. Thus, after loading, the ionoStack and regular InSAR stack (ifgramStack) will have the same dimension.
But if you have {xstep, ystep}<10 here, then the downsampling for iono will be less than 1. The code will just skip downsampling the iono files. Then your iono stack and regular InSAR stack will have different size. You will need to sample them by yourself later on when you want to difference them. So unless you already sample the topsStack products using gdal externally, just always set {xstep, ystep} = {10,10} to save hassle.

**Reminders**

- [x] Pass Codacy code review (green)
- [x] Pass Circle CI test (green)
- [x] Make sure that your code follows our style. Use the other functions/files as a basis.
- [x] If modifying functionality, describe changes to function behavior and arguments in a comment below the function declaration.
- [x] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by yuankailiu** [comment]
@mohseniaref-InSAR
Please look at our PR here!

**Comment by mohseniaref-InSAR** [comment]
Thanks so much. I have another solution, I am currently at EGU, I will contact you how to implement it in Mintpy , thanks so much for your message

**Comment by yuankailiu** [comment]
Thank you, @yunjunz for the modifications!
I will further modify the following things as we discuss offline last time:

- _When creating the stack file, fill nan for missing pairs_: this is not needed since we will have a separate ionosphere stack file. So I will remove this part of the code.
- Use consistent file names: `ionStack.h5` and save it under `inputs/`
- Use common datasetName `unwrapPhase` and `coherence` for the ionosphere stack file `ionStack.h5`. Then we don't need to add more identifiable datasetNames in several codes.
- In the template file, name the ionosphere data files as `ionUnwFile`, `ionCorFile`, `ionConnCompFile` (connComp file is optional)
- About xstep and ystep for the ionosphere file: I will write out the scaling explicitly in the code as comment, such as 
  ```
  factor   = (looks_ionIfgram)/(looks_ifgram) = 10 (for the case of topsStack)
  ionXStep = (xstep/factor)
  ionYStep = (ystep/factor)
  ```

**Comment by yuankailiu** [comment]
@yunjunz, I have modify the above suggestions from https://github.com/insarlab/MintPy/pull/780#issuecomment-1141412401

**Comment by yunjunz** [comment]
Thank you @yuankailiu, I will take a look again today.

**Review by yunjunz — APPROVED** [review]
Thank you very much for the PR @yuankailiu. All look good to me.

Re-thinking the x/ystep and its explanations in the comment, I think it's easier to keep the same values for ionStack without special treatment, for both users and developers. Thus, I have removed related parts of the code. Nevertheless, another PR to the diff.py is needed to handle the different resolutions between two inputs TS files, when applying for the iono correction.

**Pull request merged**
