### PR TITLE
Proposed fix to tsview.py to resolve issue when '--nomodel' or '--nofit' argument is used

### PR DESCRIPTION
**Pull request by bjmarfito**
Proposed fix were made to tsview.py since issues where present if '--nomodel' or '--nofit' argument were used.

**Description of proposed changes**

I've added the self.show_model logic to prevent those issues from happening.

**Reminders**

- [ ] Fix #xxxx
- [ ] Pass Codacy code review (green)
- [ ] Pass Circle CI test (green)
- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] If modifying functionality, describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by yunjunz** [comment]
@bjmarfito what was the issue?

With the current version on the main branch, if `--nomodel` is specified, the code will estimate the time func, print out the msg, but will not plot the time func prediction. I kept the printout msg on purpose, as it's useful extra info, which has been like that before the recent change. The `show_model` naming may be confusing, I plan to change it to `plot_model` in another PR.

**Comment by bjmarfito** [comment]
Apologies @yunjunz for not giving you the context regarding the issue I've encountered.

I've run the tsview.py on the  geo_timeseries_SET_ERA5_demErr.h5 using the command `tsview.py geo_timeseries_SET_ERA5_demErr.h5 --nofit`. Afterwards, I've clicked the cumulative displacement map to see the point displacement time-series. I've encountered the following errors which prevented viewing of the point displacement time-series.

```
Traceback (most recent call last):
  File "/Users/bryanmarfito/miniconda3/envs/mintpy/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 270, in process
    func(*args, **kwargs)
  File "/Users/bryanmarfito/MintPy/mintpy/tsview.py", line 895, in update_plot_timeseries
    self.plot_point_timeseries((y, x))
  File "/Users/bryanmarfito/MintPy/mintpy/tsview.py", line 813, in plot_point_timeseries
    model=self.model,
AttributeError: 'timeseriesViewer' object has no attribute 'model'
```

I've added the self.show_model to some lines of the code so displacement time-series could be displayed.

**Comment by yunjunz** [comment]
Thank you for the explanation @bjmarfito. This bug is due to the lack of initiation of `model` at the beginning of the script, which now has been fixed in the PR linked above.

**Comment by bjmarfito** [comment]
Thank you @yunjunz!

**Pull request closed without merging**
