### PR TITLE
sbApp: replace args string with list of args to support dir with whitespace

### LINKED ISSUE #395: processing fails in working directory with whitespace and "(" in path
**Description of the problem**

I have a directory on my Mac that is synced to Google Drive with the full name `/Users/fielding/Google Drive (fielding@jpl.caltech.edu)/`. I normally work by cd'ing to a symbolic link `/Users/fielding/Google_Drive_JPL`
[NepalSenD019.txt](https://github.com/insarlab/MintPy/files/4899715/NepalSenD019.txt)

 and other programs seem happy to use that as the path, but `smallbaselineApp.py` is finding the actual directory name and then choking on the "(".

**Full script that generated the error**

```
smallbaselineApp.py NepalSenD019.txt
```

**Full error message**

```

_________________________________________________
 ____    ____   _            _   _______
|_   \  /   _| (_)          / |_|_   __ \
  |   \/   |   __   _ .--. `| |-' | |__) |_   __
  | |\  /| |  [  | [ `.-. | | |   |  ___/[ \ [  ]
 _| |_\/_| |_  | |  | | | | | |, _| |_    \ '/ /
|_____||_____|[___][___||__]\__/|_____| [\_:  /
                                         \__.'

   Miami InSAR Time-series software in Python
          MintPy v1.2.2-62, 2020-07-04
_________________________________________________

--RUN-at-2020-07-09 14:47:22.680480--
Run routine processing with smallbaselineApp.py on steps: ['load_data', 'modify_network', 'reference_point', 'quick_overview', 'correct_unwrap_error', 'invert_network', 'correct_LOD', 'correct_troposphere', 'deramp', 'correct_topography', 'residual_RMS', 'reference_date', 'velocity', 'geocode', 'google_earth', 'hdfeos5']
Remaining steps: ['modify_network', 'reference_point', 'quick_overview', 'correct_unwrap_error', 'invert_network', 'correct_LOD', 'correct_troposphere', 'deramp', 'correct_topography', 'residual_RMS', 'reference_date', 'velocity', 'geocode', 'google_earth', 'hdfeos5']
--------------------------------------------------
Project name: NepalSenD019
Go to work directory: /Users/fielding/Google Drive (fielding@jpl.caltech.edu)/Tibet-Drive/ARIA-S1/Nepal_D019
copy default template file /Users/fielding/tools/mintpy/mintpy/defaults/smallbaselineApp.cfg to work directory
read custom template file: /Users/fielding/Google Drive (fielding@jpl.caltech.edu)/Tibet-Drive/ARIA-S1/Nepal_D019/NepalSenD019.txt
update default template based on input custom template
    mintpy.load.processor: auto --> aria
    mintpy.load.unwFile: auto --> ../stack/unwrapStack.vrt
    mintpy.load.corFile: auto --> ../stack/cohStack.vrt
    mintpy.load.connCompFile: auto --> ../stack/connCompStack.vrt
    mintpy.load.demFile: auto --> ../DEM/SRTM_3arcsec.dem
    mintpy.load.incAngleFile: auto --> ../incidenceAngle/20200601_20190514.vrt
    mintpy.load.azAngleFile: auto --> ../azimuthAngle/20200601_20190514.vrt
    mintpy.load.waterMaskFile: auto --> ../mask/watermask.msk
    mintpy.network.coherenceBased: auto --> no
    mintpy.network.keepMinSpanTree: auto --> yes
    mintpy.networkInversion.weightFunc: auto --> no
    mintpy.troposphericDelay.method: auto --> no
    mintpy.deramp: auto --> no
    mintpy.topographicResidual: auto --> no
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `mv /Users/fielding/Google Drive (fielding@jpl.caltech.edu)/Tibet-Drive/ARIA-S1/Nepal_D019/smallbaselineApp.cfg.tmp /Users/fielding/Google Drive (fielding@jpl.caltech.edu)/Tibet-Drive/ARIA-S1/Nepal_D019/smallbaselineApp.cfg'
copy NepalSenD019.txt to inputs directory for backup.
copy smallbaselineApp.cfg to inputs directory for backup.
copy NepalSenD019.txt to pic directory for backup.
copy smallbaselineApp.cfg to pic directory for backup.
read default template file: /Users/fielding/Google Drive (fielding@jpl.caltech.edu)/Tibet-Drive/ARIA-S1/Nepal_D019/smallbaselineApp.cfg


******************** step - load_data ********************
load_data.py --template /Users/fielding/Google Drive (fielding@jpl.caltech.edu)/Tibet-Drive/ARIA-S1/Nepal_D019/smallbaselineApp.cfg /Users/fielding/Google Drive (fielding@jpl.caltech.edu)/Tibet-Drive/ARIA-S1/Nepal_D019/NepalSenD019.txt --project NepalSenD019
SAR platform/sensor : Sen
processor: isce
Traceback (most recent call last):
  File "/Users/fielding/tools/mintpy/mintpy/smallbaselineApp.py", line 1117, in <module>
    main()
  File "/Users/fielding/tools/mintpy/mintpy/smallbaselineApp.py", line 1107, in main
    app.run(steps=inps.runSteps, plot=inps.plot)
  File "/Users/fielding/tools/mintpy/mintpy/smallbaselineApp.py", line 1036, in run
    self.run_load_data(sname)
  File "/Users/fielding/tools/mintpy/mintpy/smallbaselineApp.py", line 362, in run_load_data
    mintpy.load_data.main(scp_args.split())
  File "/Users/fielding/tools/mintpy/mintpy/load_data.py", line 624, in main
    inpsDict = read_inps2dict(inps)
  File "/Users/fielding/tools/mintpy/mintpy/load_data.py", line 174, in read_inps2dict
    if inpsDict['autoPath']:
KeyError: 'autoPath'
```

**System information**

* Operating system: MacOS 10.14.6
* Version of Python and relevant dependencies if applicable
* Version of MintPy (output of `smallbaselineApp.py -v`): MintPy release version v1.2.2-62, release date 2020-07-04
* Your custom / default template file (`smallbaselineApp.cfg`):

### PR DESCRIPTION
**Pull request by yunjunz**
**Description of proposed changes**

+ `smallbaselineApp`: for all sub-module main() calls, compose the list of arguments directly, instead of composing the arguments in long string then split, to support directory with whitespace.

+ replace most of the `os.system()` and `subprocess.Popen()` calls with pythonic func call.

**Reminders**

- [x] Fix #395 
- [x] Pass Codacy code review (green)
- [x] Pass Circle CI test (green)
- [x] Make sure that your code follows our style. Use the other functions/files as a basis.
- [x] If modifying functionality, describe changes to function behavior and arguments in a comment below the function declaration.
- [x] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by yunjunz** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ mintpy/save_hdfeos5.py  -10
         

Clones added
============
- mintpy/smallbaselineApp.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/insarlab/MintPy/pullRequest?prid=5838019&bid=19114903)

**Comment by EJFielding** [comment]
This is a lot more changes than I expected would be necessary for solving the whitespace problem, but I guess some were for other purposes. Thanks again @yunjunz

**Comment by EJFielding** [comment]
@yunjunz Did you change the requirements for reading the ARIA stacks? When I run this new version on the output from `ariaTSsetup.py`, it gives an error in the load_data step:
```
******************** step - load_data ********************
read options from template file: smallbaselineApp.cfg
usage: smallbaselineApp.py [-h] [-t TEMPLATE_FILE] [--update]
                           [-o OUTFILE OUTFILE] [-s STACKDIR] [-u UNWFILE]
                           [-c CORFILE] [-l CONNCOMPFILE] [-d DEMFILE]
                           [-i INCANGLEFILE] [-a AZANGLEFILE]
                           [--water-mask WATERMASKFILE]
ERROR: required dataset "unwFile" not found in: ../stack/unwrapStack.vrt.
```

**Comment by yunjunz** [comment]
In this PR, only the last commit is relevant for the bugfix (I was being lazy on separating them into different PRs).

No, I did not change things within prep_aria.py, and my local testing with ARIA products went through as expected until 'modify_network' (I did not continue further).

@EJFielding, the error message you showed above does not make sense to me. Could you show the full message here? I assume you are still running the same dataset as in #395.

**Comment by EJFielding** [comment]
@yunjunz Yes, this is the same Nepal dataset as in #395 with the same input file. Sorry if this is not the right place to comment. I get the error when running `prep_aria.py` directly:
```
prep_aria.py -t NepalSenD019.txt
read options from template file: NepalSenD019.txt
usage: prep_aria.py [-h] [-t TEMPLATE_FILE] [--update] [-o OUTFILE OUTFILE]
                    [-s STACKDIR] [-u UNWFILE] [-c CORFILE] [-l CONNCOMPFILE]
                    [-d DEMFILE] [-i INCANGLEFILE] [-a AZANGLEFILE]
                    [--water-mask WATERMASKFILE]
ERROR: required dataset "unwFile" not found in: ../stack/unwrapStack.vrt.
```
I looked at some of the code, and I did not find anything about a dataset "unwFile".

**Comment by yunjunz** [comment]
Hi @EJFielding, having comments here is good. I tried a similar command as below and can not reproduce the error. 

```
(base) yunjunz:~/test>$ pwd
/Users/yunjunz/test
(base) yunjunz:~/test>$ python -c "import os; print(os.getcwd())"
/Users/yunjunz/data/test/test (2)/SanFranSenDT42/mintpy
(base) yunjunz:~/test>$ prep_aria.py -t SanFranSenDT42.txt 
```

There is one potential bug related with the `--update` option, https://github.com/yunjunz/MintPy/commit/1dc34fb87407120602604aa7a53d2bcaed928dae, but I don't think this is related to the error message you have.

Cc @dbekaert and @ehavazli to see if they have an idea.

**Comment by EJFielding** [comment]
Sorry, now I found my mistake. The template file had `../stack/unwrapStack.vrt` but I was trying to run it from the same directory where the `stack` was located instead of a subdirectory. I created a `MintPy` subdirectory and ran the command there and it works fine. Pilot error.

**Comment by EJFielding** [comment]
I am glad that I posted this issue earlier as I made the same mistake again ;-).

**Comment by yunjunz** [comment]
Hi @EJFielding, please feel free to issue a PR for your recommendation. The relevant line of code is [prep_aria.py#L138](https://github.com/insarlab/MintPy/blob/main/mintpy/prep_aria.py#L138).

Using an absolute path could use less error-prone as well.

**Comment by EJFielding** [comment]
In this particular case yesterday, I was running MintPy on the OpenSARlab server in a Jupyter notebook, so using an absolute path would be problematic. I also found out that they have the MintPy release 1.2.2 from April 2020 at the moment.

**Comment by dbekaert** [comment]
@EJFielding can check with Franz. Our goal was to run the latest version 1.2.3 (cut for the course), so not sure. Also note that OSL does not pull from dev repo's for stability reasons. So latest commits are generally not at OSL. The released version of mintpy and aria-tools are being checked in advanced for compatibility when deployed on OSL.

**Pull request merged**
