### PR TITLE
save_hdfeos5.py and smallbaselineApp.py: add avgSpatialCoh.h5 to S1*.he5 file

### PR DESCRIPTION
**Pull request by ranneylxr**
**Description of proposed changes**

save_hdfeos5.py and smallbaselineApp.py: add avgSpatialCoh.h5 to S1*.he5 file

**Reminders**

- [x] Pass Codacy code review (green)
- [x] Pass Circle CI test (green)
- [x] Make sure that your code follows our style. Use the other functions/files as a basis.
- [x] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by yunjunz** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- mintpy/save_hdfeos5.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/insarlab/MintPy/pullRequest?prid=6132317&bid=20055227)

**Comment by ranneylxr** [comment]
Hi Yunjun,
The added clones are for telling people that script adds avgSpatialCoh.h5 into hdfeos files. I use these lines  just as what you wrote for 'mask.h5', 'timeseries.h5' files etc. Are there any problems? Thank you.

**Comment by yunjunz** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- mintpy/save_hdfeos5.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/insarlab/MintPy/pullRequest?prid=6132317&bid=20055227)

**Review by yunjunz — APPROVED** [review]
Thank you @ranneylxr. This looks great.

**Pull request merged**
