### PR TITLE
Fix save_gdal.py reflection bug

### PR DESCRIPTION
**Pull request by 4restwilliams**
save_gdal.py returned reflected version of input dataset. Array is now flipped before ingestion into GDAL to fix this issue.

Also updated example section

### CODE REVIEW

**Comment by yunjunz** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mintpy/save_gdal.py  7
         

Clones added
============
- mintpy/save_gdal.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/insarlab/MintPy/pullRequest?prid=5708885&bid=18683523)

**Comment by yunjunz** [comment]
Hi @4restwilliams, the 2D matrix is also reversed in the [main()](https://github.com/insarlab/MintPy/blob/master/mintpy/save_gdal.py#L128), what's rationale to reverse it again inside in the `array2raster()`?

**Comment by 4restwilliams** [comment]
Hi @yunjunz my mistake. I forgot that we already reversed the array in `main()`. I'll fix this bug by just removing the original reverse in `main()`.

**Comment by yunjunz** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mintpy/save_gdal.py  7
         

Clones added
============
- mintpy/save_gdal.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/insarlab/MintPy/pullRequest?prid=5708885&bid=18683523)

**Comment by 4restwilliams** [comment]
Would you mind checking that save_gdal.py is now working correctly? I've been working with prep_fringe.py outputs and I want to make sure that the error was in save_gdal.py, not in prep_fringe.py. I've found that calling save_gdal.py on the height dataset of a geometryGeo.h5 file to be a quick way to check this.

**Comment by yunjunz** [comment]
Hi @4restwilliams, there are conflicts between your branch and the upstream default one, making it confusing to know the latest version. Could you resolve it using `git rebase` and `git push -f`? 

Here is a tutorial if you are not familiar with rewriting git history: https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history

**Comment by yunjunz** [comment]
@4restwilliams From my testing with the Fernandina example dataset, no array reflection is needed. 

Screen Shot 2020-06-17 at 5 40 00 PM

**Comment by yunjunz** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mintpy/save_geotiff.py  3
         

Clones added
============
- mintpy/save_gdal.py  1
- mintpy/save_geotiff.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/insarlab/MintPy/pullRequest?prid=5708885&bid=18683523)

**Comment by 4restwilliams** [comment]
@yunjunz I believe I have fixed the merge issues. Also, I apologize for the messy commits. This was my first time using rebase and it wasn't done cleanly. If you prefer, I can close this pull request and open a new one with a clean history to fix this issue.

**Comment by yunjunz** [comment]
Hi @4restwilliams, no worries at all, we all went through that process. 

The current final version of this PR still has a few unwanted changes from recent other commits: https://github.com/insarlab/MintPy/pull/379/files. Could you try the following for rebase again?

```bash
git fetch upstream
git rebase -i HEAD~{number-of-commits-on-your-branch-ahead-of-insarlab/master}   #and squash/fixup all of them into one
git push -f
```

If the above does not work, another PR could a simple way.

**Comment by yunjunz** [comment]
Hi @4restwilliams, any update on this PR?

**Comment by yunjunz** [comment]
I included this bugfix in #400 so that it could be included in the next released version.

**Pull request closed without merging**
