### PR TITLE
modify some MinitPy code to make it work with the hyp3 product

### PR DESCRIPTION
**Pull request by cirrusasf**
**Description of proposed changes**
The original mintpy does not work with hyp3 product. The hyp3 product normally is in the projection of WGS 84 / UTM zone 53N. The  step "correct_troposphere" downloads the ERA5 data. These grib data normally are in GEO coordinates. The tropo_pyaps3.py only processes the data with GEO coordinates, which is not the case for the hyp3 product. So tropo_pyaps3.py needs modification. Also prep_hyp3.py needs modify to accept the Inc_angle file.

**Reminders**

- [ ] Fix #xxxx
- [ ] Pass Codacy code review (green)
- [ ] Pass Circle CI test (green)
- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.
- [ ] If modifying functionality, describe changes to function behavior and arguments in a comment below the function declaration.
- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Review by yunjunz — COMMENTED** [review]
Thank you @cirrusasf! I think the `convert2degree()` is gonna be handy for the wider users. However, adding a new folder and script for it alone seems unnecessary to me. Below are my suggestions, let me know what do you think please.

1. Move the `convert2degree()` to [utils0.py#L234](https://github.com/insarlab/MintPy/blob/main/mintpy/utils/utils0.py#L234) and call it in [tropo_pyaps3.py#L667](https://github.com/insarlab/MintPy/blob/main/mintpy/tropo_pyaps3.py#L667). It's where the other low level geometry related functions are. Since this functionality is very similar to [utm.to_latlon()](https://github.com/Turbo87/utm#utm-to-latitudelongitude), thus, maybe considering renaming to `to_latlon()` for simplicity?
2. Since `snwe_in_degree()` is used only once, I would recommend to merge it into [tropo_pyaps3.get_bounding_box()](https://github.com/insarlab/MintPy/blob/main/mintpy/tropo_pyaps3.py#L454) for a uniform API, so that no change is needed in the main().

**Comment by cirrusasf** [comment]
Hi Yunujun,

I will follow your instructions to do that. Thank you very much!

Jiang

**Comment by cirrusasf** [comment]
I have no idea how should I do to pass the tests. Can you help me with that?

**Comment by yunjunz** [comment]
Thank you @cirrusasf. The readability of the change improved a lot.

I have a few very minor suggestions, it would be much easier for me to adjust it directly. Could you give me permission to edit this PR on the right side of this page?

**Comment by cirrusasf** [comment]
Moving this to insarlab/MintPy#567 to allow edits by maintainers (not possible with our organizational fork).

**Comment by cirrusasf** [comment]
Hi YunJun,

I grant you the permission to do that.

Jiang

**Comment by yunjunz** [comment]
Thank you @cirrusasf.

**Pull request closed without merging**
