### PR TITLE
Block by block Writing with Dask

### PR DESCRIPTION
**Pull request by Ovec8hkin**
Implemented block-by-block reading and writing with dask in `ifgram_inversion.py` #347. This addition makes `ifgram_inversion` now both computationally and memory efficient. The amount of memory that is used by `ifgram_inversion` can be controlled using the `--memory` command line option or by setting `mintpy.networkInversion.memorySize` in the `smallbaselineApp.cfg` file. 

**Reminders**

- [x] Pass Codacy code review (green)
- [x] Pass testing with `$MINTPY_HOME/test/test_smallbaselineApp.py`
- [x] Make sure that your code follows our style. Use the other functions/files as a basis.
- [x] If modifying functionality, describe changes to function behavior and arguments in a comment below the function declaration.
- [x] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by yunjunz** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- mintpy/ifgram_inversion.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/insarlab/MintPy/pullRequest?prid=5553252&bid=18207835)

**Comment by yunjunz** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- mintpy/ifgram_inversion.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/insarlab/MintPy/pullRequest?prid=5553252&bid=18207835)

**Comment by yunjunz** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mintpy/objects/cluster.py  3
         

Clones added
============
- mintpy/ifgram_inversion.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/insarlab/MintPy/pullRequest?prid=5553252&bid=18207835)

**Comment by yunjunz** [comment]
Hi @Ovec8hkin, I got the following popup window while running `ifgram_inversion.py --parallel`. Any idea?

Screen Shot 2020-05-19 at 6 59 21 PM

**Comment by Ovec8hkin** [comment]
I presume it’s dask asking if you will allow it access to an internal inbound network, as dask local cluster establishes and runs via a TCP local network it creates.

**Comment by yunjunz** [comment]
Is there a way to get rid of this?

**Comment by Ovec8hkin** [comment]
Doubtful. It’s something with your system. I don’t get any message like that on mine.

**Comment by yunjunz** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mintpy/objects/cluster.py  3
         

Clones added
============
- mintpy/ifgram_inversion.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/insarlab/MintPy/pullRequest?prid=5553252&bid=18207835)

**Comment by yunjunz** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mintpy/objects/cluster.py  3
         

Clones added
============
- mintpy/ifgram_inversion.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/insarlab/MintPy/pullRequest?prid=5553252&bid=18207835)

**Comment by 2gotgrossman** [comment]
It looks like I am too late to the conversation by 20 minutes, but it does sound like an OS problem. @yunjunz what OS version are you running?

**Comment by yunjunz** [comment]
Hi @2gotgrossman, I am using macOS Mojave.

**Comment by yunjunz** [comment]
I ran the test on Fernandina dataset again, on both python environment installed by conda and by macports, this popup windows seems not showing anymore.

**Pull request merged**
