### PR TITLE
Proposed changes to solid_earth_tides.py and tropo_pyaps3.py w.r.t. HyP3 products

### LINKED ISSUE #575: SET not working on HyP3 products due to missing azimuth angle file
**Description of the problem**
I am generating time-series from HyP3 interferograms and was trying to correct for solid earth tides. However, the azimuthAngle file is missing from the geometryGeo.h5 since the azimuth file is not included on the HyP3. Though, the geometryGeo.h5 has a heading value. 

I'm thinking if I should also inform the HyP3 team regarding this issue.

**Full script that generated the error**

```
smallbaselineApp.py 2019_Cotabato.cfg
```

**Full error message**

```
******************** step - correct_SET ********************
Input data seems to be geocoded. Lookup file not needed.

solid_earth_tides.py /Volumes/BJM_Personal/Cotabato_EQ_2019/Sentinel-1/HyP3/mintpy/timeseries.h5 -g /Volumes/BJM_Personal/Cotabato_EQ_2019/Sentinel-1/HyP3/mintpy/inputs/geometryGeo.h5 -o /Volumes/BJM_Personal/Cotabato_EQ_2019/Sentinel-1/HyP3/mintpy/timeseries_SET.h5 --update
read/prepare LOS geometry from file: /Volumes/BJM_Personal/Cotabato_EQ_2019/Sentinel-1/HyP3/mintpy/inputs/geometryGeo.h5
read incidence / azimuth angle
Traceback (most recent call last):
  File "/Users/bryanmarfito/MintPy/mintpy/smallbaselineApp.py", line 1255, in <module>
    main(sys.argv[1:])
  File "/Users/bryanmarfito/MintPy/mintpy/smallbaselineApp.py", line 1237, in main
    app.run(steps=inps.runSteps)
  File "/Users/bryanmarfito/MintPy/mintpy/smallbaselineApp.py", line 1050, in run
    self.run_solid_earth_tides_correction(sname)
  File "/Users/bryanmarfito/MintPy/mintpy/smallbaselineApp.py", line 742, in run_solid_earth_tides_correction
    solid_earth_tides.main(iargs)
  File "/Users/bryanmarfito/MintPy/mintpy/solid_earth_tides.py", line 341, in main
    calc_solid_earth_tides_timeseries(ts_file=inps.dis_file,
  File "/Users/bryanmarfito/MintPy/mintpy/solid_earth_tides.py", line 248, in calc_solid_earth_tides_timeseries
    inc_angle, head_angle, atr_geo = prepare_los_geometry(geom_file)
  File "/Users/bryanmarfito/MintPy/mintpy/solid_earth_tides.py", line 129, in prepare_los_geometry
    az_angle  = readfile.read(geom_file, datasetName='azimuthAngle')[0]
  File "/Users/bryanmarfito/MintPy/mintpy/utils/readfile.py", line 222, in read
    data = read_hdf5_file(fname,
  File "/Users/bryanmarfito/MintPy/mintpy/utils/readfile.py", line 292, in read_hdf5_file
    raise ValueError('input dataset {} not found in file {}'.format(datasetName, fname))
ValueError: input dataset ['azimuthAngle'] not found in file /Volumes/BJM_Personal/Cotabato_EQ_2019/Sentinel-1/HyP3/mintpy/inputs/geometryGeo.h5
```

**System information**

* Operating system: macOS
* Python environment: conda
* Version of MintPy: https://github.com/insarlab/MintPy/commit/2e3dcea0415dd96f02dbcafc7d36aafcbee6ef69
* Your custom / default template file (if the bug is related to a specific dataset): 
[2019_Cotabato.cfg.txt](https://github.com/insarlab/MintPy/files/6641908/2019_Cotabato.cfg.txt)

### PR DESCRIPTION
**Pull request by bjmarfito**
**Description of proposed changes**

- Changes are made to solid_earth_tides.py to properly compute the pixel spacing from the HyP3 products (see issue https://github.com/insarlab/MintPy/issues/575) and to convert incidence angle from radians to degrees if HyP3 is detected as the processor.
- Changes are made to tropo_pyaps3.py to convert incidence angle from radians to degrees if HyP3 is detected as the processor.

I've got the template for editing the solid_earth_tides.py from @cirrusasf (PR https://github.com/insarlab/MintPy/commit/4ee12c648469937369c968b07e2583f7df8d297e). Pls. check if the changes I've made are correct or if I need to edit these changes. 

**Reminders**

- [x] Fix #575
- [x] Pass Codacy code review (green)
- [x] Pass Circle CI test (green)
- [x] Make sure that your code follows our style. Use the other functions/files as a basis.
- [x] If modifying functionality, describe changes to function behavior and arguments in a comment below the function declaration.
- [x] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Review by yunjunz — CHANGES_REQUESTED** [review]
Thank you @bjmarfito for addressing these issues.

1. regarding the different unit of angle from hyp3, I would prefer to convert them in the very beginning during the data loading (writing HDF5 file) process, so that the loaded dataset is consistent with other InSAR processors. I would suggest adding `meta['UNIT'] = 'radian'` in prep_hyp3.py while writing the RSC file, and in [stackDict.py](https://github.com/insarlab/MintPy/blob/3813901115a23f31f2dde1a48395e0c921aa655a/mintpy/objects/stackDict.py#L616) check the unit for angle dataset and convert it.
2. As for the Y/X_FIRST/STEP part of the change, I guess moving them [here](https://github.com/insarlab/MintPy/blob/3813901115a23f31f2dde1a48395e0c921aa655a/mintpy/solid_earth_tides.py#L154) is more suitable.
3. could you resolve the issues flagged by codacy and circiel ci? All checkings should be passed (green).

**Comment by bjmarfito** [comment]
Pls. check @ yunjunz if the changes are ok with you. I've followed your advise to convert the incidence angle during loading of the data. I don't know if you're gonna like it but I converted the coordinates to longitude and latitude.

Below is the result after I converted the incidence angle to degrees and the coordinates to latitude and longitude.

incidence_angle

**Comment by cirrusasf** [comment]
Hi Insarlab/Mintpy,

I am very happy you are workng on hyp3 product. I have two questions or
concerns here. In the another thread, Zhang told me our inc_map.tif is not
what the mintpy wants. He said the Inc angle is defined with respect of
zenith, not with the normal of the surface. From the attached image, I say
that the Inc angle tif is representative to the angle w.r.t normal line of
the surface of the pixel. So my question is which Inc angle is correct,
does mintpy need two versions of Inc angle tif files? 2. If the image is
located in the anti primary meridiam, change to longitude and latitude may
cause some problem.

Jiang

**Comment by yunjunz** [comment]
@cirrusasf, the incidence angle attached above is NOT what mintpy wants. The solid Earth tides and tropospheric delay calculated based on this incidence angle will be wrong.

However, I expect all the other aspects to be applicable for the future right incidence angle, so I am considering merging this PR now.

**Comment by yunjunz** [comment]
@bjmarfito the angle data conversion looks good.

I would prefer to keep the original UTM coordinates as it is because 1) users might want to use the specific projection for their own reason (e.g. UTM is more suitable and WGS84 for polar regions), it is more tolerant for mintpy to not force that; 2) NISAR is gonna use UTM projection so it's a good practice to test it now; 3) UTM to WGS84 projection need more careful handling than Y/X_FIRST/STEP alone for precise geolocation. Thus, I like the previous handling in solid_earth_tides.py better.

**Comment by bjmarfito** [comment]
I've followed your suggestion @yunjunz to keep using the UTM coordinates instead of the geographic coordinates. 

@cirrusasf, we're hoping to use HyP#3 to monitor volcano deformation and I'm hoping that your team will be able to incorporate the incidence angle acceptable by MintPy soon.

Below is the figure of the test data for the incidence angle in UTM coordinates.

Figure

**Review by yunjunz — APPROVED** [review]
Looks all good to me. Thank you @bjmarfito!

**Comment by bjmarfito** [comment]
You're welcome @yunjunz!

**Comment by cirrusasf** [comment]
Hi Insarlab/Mintpy,

We will address the inc angle ASAP.

Jiang

**Pull request merged**
