### PR TITLE
ifg_inv_patch: simplify the input arguments

### PR DESCRIPTION
**Pull request by yunjunz**
**Description of proposed changes**

+ simplify the input arguments of ifgram_inversion_patch() to support #354 

+ add `mintpy.compute.*` option for memory and parallel computing related parameters @Ovec8hkin 

+ use `cluster = no` to turn OFF parallel processing, to avoid `parallel = yes / no` option, following @falkamelung's suggestion.

+ turn ON parallel with `cluster = local` as default.

**Reminders**

- [x] Pass Codacy code review (green)
- [x] Pass testing with `$MINTPY_HOME/test/test_smallbaselineApp.py`
- [x] Make sure that your code follows our style. Use the other functions/files as a basis.
- [x] If modifying functionality, describe changes to function behavior and arguments in a comment below the function declaration.

### CODE REVIEW

**Comment by yunjunz** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones removed
==============
+ mintpy/ifgram_inversion.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/insarlab/MintPy/pullRequest?prid=5581802&bid=18296368)

**Comment by Ovec8hkin** [comment]
Yunjun, can we rollback the changes to ifgram_inversion.py for a few hours? I think there is a better way to remove the use of the `parallel_ifgram_inversion_patch` function without changing the method signature of `ifgram_inversion_patch`.

**Comment by yunjunz** [comment]
Hi @Ovec8hkin, I like the new input arguments for ifgram_inversion_patch(), even without our desire for dask, because it's much shorter. I made the previous version when the functionality is not as complex as now, the number of arguments has grown a lot since then. It does not make much sense to me to use a lot of arguments in order to avoid using namespace.

If you still prefer the old way, feel free to create a branch from the master before this merge.

**Comment by Ovec8hkin** [comment]
Personally, I think it’s more explicit to use the argument names directly so that it’s clear what data is needed and being used. By passing the entire inps namespace object to the function, it is not directly clear what data is actually needed by the function anymore, and a lot of data that is not needed is being sent.

**Comment by yunjunz** [comment]
I agree that's cleaner. I should have waited longer before merging!

**Pull request merged**
