### PR TITLE
prep_hyp3: update to be compatible with current hyp3 products

### PR DESCRIPTION
**Pull request by forrestfwilliams**
**Description of proposed changes**
Related to issue #540

- removes hard coding of EARTH_RADIUS and HEIGHT
- enables use of HyP3 DEM and incidence angle products
- reorganizes main() and add_hyp3_metadata() functions
- updates help information

**Reminders**

- [x] Pass Codacy code review (green)
- [x] Pass Circle CI test (green)
- [x] Make sure that your code follows our style. Use the other functions/files as a basis.
- [x] If modifying functionality, describe changes to function behavior and arguments in a comment below the function declaration.
- [x] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by forrestfwilliams** [comment]
Both tests appear to have failed because FernandinaSenDT128.tar.xz could not be retrieved from Zenodo.org

**Comment by yunjunz** [comment]
Thank you @forrestfwilliams. The modification of `prep_hyp3.py` looks great. Could you please also update the brief instruction and template options in the `docs/dir_structure.md`?

**Comment by forrestfwilliams** [comment]
@yunjunz I've updated `docs/dir_structure.md` and uploaded an updated version of `tongariroSen.zip` to your Box folder!

**Review by yunjunz — APPROVED** [review]
Thank you @forrestfwilliams for the update and the test data. Everything looks good to me.

**Pull request merged**
