### PR TITLE
dep/doc: add tab completion via `argcomplete`

### PR DESCRIPTION
**Pull request by yunjunz**
**Description of proposed changes**

+ add `argcomplete` to the dependency for tab completion capability, which is implemented in #823 and described in #1041. This package is light (only depends on pure Python), and available on pip and conda-forge (as noarch package).
   - requirements.txt: add argcomplete
   - setup.py: move argcomplete from optional to required

+ docs/installation.md: add "tab complete sub-commands" as another sub-section in Post-Installation Setup.

**Reminders**

- [x] Pass Pre-commit check (green)
- [x] Pass Codacy code review (green)
- [x] Pass [Circle CI test](https://app.circleci.com/pipelines/github/yunjunz/MintPy/2277/workflows/218deb04-7c97-44fd-9add-15044815f908/jobs/2285) (green)
- [x] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Review by avalentino — APPROVED** [review]
The changes are good to me.
Probably you may want to point out that, on Mac OSX, `argcomplete >= 3.0` works perfectly on the default shell `zsh`. In that case no workaround is needed.

**Comment by falkamelung** [comment]
I was surprised that you can call mintpy functions using `mintpy` although there is no script/file called `mintpy`. Some explanation of why this works could be helpful.

**Comment by scottstanie** [comment]
> I was surprised that you can call mintpy functions using `mintpy` although there is no script/file called `mintpy`. Some explanation of why this works could be helpful.

These come from the Mintpy [entry points](https://packaging.python.org/en/latest/specifications/entry-points/#use-for-scripts), which is the typical way a python package can make a command line tool available when you `pip install` the package (without messing with any `$PYTHONPATH` or `$PATH` environment variables). https://setuptools.pypa.io/en/latest/userguide/entry_point.html#console-scripts gives a minimal example to see how that works

**Comment by yunjunz** [comment]
> I was surprised that you can call mintpy functions using `mintpy` although there is no script/file called `mintpy`. Some explanation of why this works could be helpful.

This nice feature was introduced in version 1.5.0 by @avalentino. It's very similar to the latest GMT. I have not advertised it heavily yet, as it may be confusing to users who are used to the `view.py` style.

**Pull request merged**
