### PR TITLE
clean up insarmaps/dev scripts

### PR DESCRIPTION
**Pull request by yunjunz**
**Description of proposed changes**

This PR has the following changes for a cleaner mintpy root directory:

1) move all insarmaps related script into `mintpy/insarmaps` folder. 

The related scripts are as below:
+ add_attribute_insarmaps.py
+ hdfeos5_2insarmaps.py
+ hdfeos5_2json_mbtiles.py
+ inarmaps_query.py
+ json_mbtiles2insarmaps.py

@falkamelung To keep running these scripts, one needs to add `$MINTPY_HOME/mintpy/insarmaps` to `$PATH`. Everything else should be the same.

2) add `mintpy/legacy/gui` folder and move all the gui related script into it.

3) move the following two scripts into dev as they are not mintpy directly related.
+ process_isce_stack.py
+ split_jobs.py

**Reminders**

- [x] Pass Codacy code review (green)
- [x] Pass testing with `$MINTPY_HOME/test/test_smallbaselineApp.py`

### CODE REVIEW

**Comment by yunjunz** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mintpy/insarmaps/json_mbtiles2insarmaps.py  11
- mintpy/insarmaps/hdfeos5_2json_mbtiles.py  11
- mintpy/insarmaps/add_attribute_insarmaps.py  4
         

Clones added
============
- mintpy/insarmaps/add_attribute_insarmaps.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/insarlab/MintPy/pullRequest?prid=5497753&bid=18019406)

**Comment by yunjunz** [comment]
Hi @falkamelung, do you see issues with this change? If you, I will go forward and merge it.

**Comment by yunjunz** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mintpy/insarmaps/json_mbtiles2insarmaps.py  11
- mintpy/insarmaps/hdfeos5_2json_mbtiles.py  11
- mintpy/insarmaps/add_attribute_insarmaps.py  4
         

Clones added
============
- mintpy/insarmaps/add_attribute_insarmaps.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/insarlab/MintPy/pullRequest?prid=5497753&bid=18019406)

**Comment by falkamelung** [comment]
That is fine. So the next step would be to completely remove them from mintpy and start a insarmaps repository, I suppose?


On May 9, 2020, at 8:29 PM, Zhang Yunjun <notifications@github.com<mailto:notifications@github.com>> wrote:


Description of proposed changes

This PR has the following changes for a cleaner mintpy root directory:

  1.  move all insarmaps related script into mintpy/insarmaps folder.

The related scripts are as below:

  *   add_attribute_insarmaps.py
  *   hdfeos5_2insarmaps.py
  *   hdfeos5_2json_mbtiles.py
  *   inarmaps_query.py
  *   json_mbtiles2insarmaps.py

@falkamelung<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffalkamelung&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Ce64d4b999a2545ea923408d7f4792bf5%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637246673584185578&sdata=LQkERevwI9QEgdLeITFMRTXX6uTzzVeZJEoRCABh8BI%3D&reserved=0> To keep running these scripts, one needs to add $MINTPY_HOME/mintpy/insarmaps to $PATH. Everything else should be the same.

  1.  add mintpy/legacy/gui folder and move all the gui related script into it.

  2.  move the following two scripts into dev as they are not mintpy directly related.

  *   process_isce_stack.py
  *   split_jobs.py

Reminders

  *    Pass Codacy code review (green)
  *    Pass testing with $MINTPY_HOME/test/test_smallbaselineApp.py

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/insarlab/MintPy/pull/341<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finsarlab%2FMintPy%2Fpull%2F341&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Ce64d4b999a2545ea923408d7f4792bf5%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637246673584195569&sdata=%2FSJoK9rpbB5xk8XJP3xLNkjdYBNSIff8irFXrFC46CY%3D&reserved=0>

Commit Summary

  *   clean up insarmaps/dev scripts

File Changes

  *   R mintpy/dev/process_isce_stack_v1.py<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finsarlab%2FMintPy%2Fpull%2F341%2Ffiles%23diff-769d3eafd4821042c7fcb10d61e9e2b5&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Ce64d4b999a2545ea923408d7f4792bf5%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637246673584195569&sdata=QDOqbhz7b3VZckW2kKWH7PyLD5%2B9xu3gDwZUbgnidd8%3D&reserved=0> (0)
  *   R mintpy/dev/split_jobs.py<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finsarlab%2FMintPy%2Fpull%2F341%2Ffiles%23diff-f8a412ab597671a6b2ddec6725a6fb02&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Ce64d4b999a2545ea923408d7f4792bf5%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637246673584205565&sdata=n265qtFPPtZ38zqd%2FfFYJ1ZuHwRa2T68Pp0YyB%2FsPtE%3D&reserved=0> (0)
  *   R mintpy/insarmaps/add_attribute_insarmaps.py<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finsarlab%2FMintPy%2Fpull%2F341%2Ffiles%23diff-8d6541c2353b33bd8f07be5c7027c1bb&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Ce64d4b999a2545ea923408d7f4792bf5%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637246673584205565&sdata=VWgn6SKDsuigqPEfFYs0ulb12yf3K%2BwGECVKaMJtL58%3D&reserved=0> (3)
  *   R mintpy/insarmaps/hdfeos5_2insarmaps.py<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finsarlab%2FMintPy%2Fpull%2F341%2Ffiles%23diff-e70a2e7695b245986aaedfa8cd747e96&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Ce64d4b999a2545ea923408d7f4792bf5%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637246673584215561&sdata=Gx8JIOJOYbUc%2BqvxN6kDXT2hzpSP7qhZklBSCXjZ21A%3D&reserved=0> (0)
  *   R mintpy/insarmaps/hdfeos5_2json_mbtiles.py<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finsarlab%2FMintPy%2Fpull%2F341%2Ffiles%23diff-9fdcd0011c44d8986b0142722d59699d&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Ce64d4b999a2545ea923408d7f4792bf5%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637246673584225557&sdata=aXZ7PWqp%2FAKh6lPzhb79gexJwbH6feayOIkf4SSYaFU%3D&reserved=0> (13)
  *   R mintpy/insarmaps/insarmaps_query.py<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finsarlab%2FMintPy%2Fpull%2F341%2Ffiles%23diff-5fcb380769001afc86f1c41aee673e64&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Ce64d4b999a2545ea923408d7f4792bf5%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637246673584225557&sdata=WrwaOsV7pFejpwY%2BChboPqH7hlzQt4E9Sav%2FFl3YJS0%3D&reserved=0> (0)
  *   R mintpy/insarmaps/json_mbtiles2insarmaps.py<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finsarlab%2FMintPy%2Fpull%2F341%2Ffiles%23diff-bf0b28e4eaaa38e93386fe364f07f8ed&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Ce64d4b999a2545ea923408d7f4792bf5%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637246673584235549&sdata=Hxkiw6Qyss0Hny1l8eS6u5RyVCI10u%2FFizXbjinUVSU%3D&reserved=0> (9)
  *   R mintpy/legacy/gui/info_gui.py<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finsarlab%2FMintPy%2Fpull%2F341%2Ffiles%23diff-407cc1e782f03e6ccfa46bbb6c940697&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Ce64d4b999a2545ea923408d7f4792bf5%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637246673584235549&sdata=vv2PzcMg%2Fi5UdbvIY0HlN34xZIF3KPiRPo9N%2FhKAArw%3D&reserved=0> (0)
  *   R mintpy/legacy/gui/pysar_gui.py<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finsarlab%2FMintPy%2Fpull%2F341%2Ffiles%23diff-beab60fe4ed98826d8af1cbda6be6ce1&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Ce64d4b999a2545ea923408d7f4792bf5%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637246673584245547&sdata=5L5Zx5VMWN5N8P8Rp95oTmFzKRXine%2B85bAMn63k970%3D&reserved=0> (0)
  *   R mintpy/legacy/gui/tsview_dev.py<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finsarlab%2FMintPy%2Fpull%2F341%2Ffiles%23diff-55110e7ea75c45b0a1cae04549884aac&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Ce64d4b999a2545ea923408d7f4792bf5%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637246673584245547&sdata=2iVg%2FXRyXmPcBYd1SB%2FTXzuMcjmltpL04gLt%2FSaS7PM%3D&reserved=0> (0)
  *   R mintpy/legacy/gui/tsview_gui.py<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finsarlab%2FMintPy%2Fpull%2F341%2Ffiles%23diff-0b9867e4152c8669493269a604c2ec9a&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Ce64d4b999a2545ea923408d7f4792bf5%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637246673584255545&sdata=cfEGlJ99wU%2FQAk4qageMfWeWaLjdXl7QqLzeJeNUY04%3D&reserved=0> (0)
  *   R mintpy/legacy/gui/view_gui.py<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finsarlab%2FMintPy%2Fpull%2F341%2Ffiles%23diff-12f7a7772edafc409e4b06b3f569bb7d&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Ce64d4b999a2545ea923408d7f4792bf5%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637246673584265538&sdata=gcSiC7ra69kk8S2NURiNVsWhBwB77xFhju0JPg1bcc0%3D&reserved=0> (0)

Patch Links:

  *   https://github.com/insarlab/MintPy/pull/341.patch<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finsarlab%2FMintPy%2Fpull%2F341.patch&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Ce64d4b999a2545ea923408d7f4792bf5%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637246673584265538&sdata=9F15W88NCla6le%2B31xRu73ASwHSsEdW9olQ5Q0XKZ1M%3D&reserved=0>
  *   https://github.com/insarlab/MintPy/pull/341.diff<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finsarlab%2FMintPy%2Fpull%2F341.diff&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Ce64d4b999a2545ea923408d7f4792bf5%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637246673584275534&sdata=MhcZ8C4FZG0Ffgr6guTLUalxC4MWHwTzSdaDzdK2xRQ%3D&reserved=0>

**Comment by yunjunz** [comment]
The next step you described sounds good to me.

**Pull request merged**
