### PR TITLE
utils: refactor time_func.py and add s1_utils.py 

### PR DESCRIPTION
**Pull request by yunjunz**
**Description of proposed changes**

This PR adds the following new features:
1. add a new dedicated utility script `utils/time_func.py` for `estimate_time_func()` (from timeseries2velocity.py) and `get_design_matrix4time_func()` (from objects/stack.py and all its sub-functions).
2. support accurate time of the day info in `THH(:)MM` style for relevant time functions (step/exp/log) for #640.
3. add a new utility script `utils/s1_utils.py` dedicated for Sentinel-1 specific functionalities, with initial content from Yunjun et al. [in prep]
4. add new example dataset `RidgecrestSenDT71` for `hyp3` from @cirrusasf (https://github.com/insarlab/MintPy-tutorial/pull/26).

**Reminders**

- [x] Pass Codacy code review (green)
- [x] Pass Circle CI / local test (green)
- [x] Make sure that your code follows our style. Use the other functions/files as a basis.
- [x] If modifying functionality, describe changes to function behavior and arguments in a comment below the function declaration.
- [x] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by yunjunz** [comment]
@yuankailiu could you please take a look at the `utils/time_func.py` related changes when you got a chance? 

Note that I added a pointer in the stack.py to the new time_func.py for backward compatibility, so I don't expect impacts on downstream code from users [would recommend switching to the new script though as it's simpler].

**Comment by yunjunz** [comment]
For book keeping, below are the estimated step function for the co-seismic deformation from the two EQs and it's displacement time-series of a pixel near the fault.

step20190706_wrap10
ts

**Comment by yuankailiu** [comment]
Thank you @yunjunz for making this much cleaner, even with the resolution down to seconds!
I checked `utils/time_func.py` and related calls from other scripts. They look good to me.

**Review by yuankailiu — APPROVED** [review]
They look good to me. I did not modify anything.

**Pull request merged**
