### PR TITLE
plot_gps: search/use geometry file for incAngle if available

### PR DESCRIPTION
**Pull request by yunjunz**
+ utils.plot.plot_gps(): search existing geometry files with incidenceAngle dataset and use it to convert GPS enu to LOS.

+ utils.utils1.get_file_list(): bug fix related with coord argument

+ utils.utils1.get_geometry_file(): add work_dir to support searching while runing script not in the directory of the input file.

### CODE REVIEW

**Comment by ehavazli** [comment]
everything seems to be working except when I specify comparison to up component
```
--gps-comp up
```

**Comment by yunjunz** [comment]
`--gps-comp up` is not really implemented, I removed this for now.

**Comment by ehavazli** [comment]
consider changing the help output of view.py to remove up option so it won't be confusing.
Have you checked the codacy review?

**Comment by yunjunz** [comment]
> consider changing the help output of view.py to remove up option so it won't be confusing.

Yes, it's removed from `utils.plot.add_gps_argument()` which is called by `view.py`. There is no extra `--gps-comp up` in view.py as far as I checked.

Thanks for the reminder of codacy suggestion.

**Pull request merged**
