### PR TITLE
asc_desc2horz_vert: add --dset option

### LINKED ISSUE #456: asc_desc2horz_vert.py only uses first dataset of input files
**Description of the problem**

The `asc_desc2horz_vert.py` script reads the first dataset of the two input files and assumes that it is `velocity`. The new version of `timeseries2velocity.py` includes the option to do a fit to a timeseries using multiple basis components and writing a number of datasets into the output `velocity.h5` file. The new components are now stored before `velocity` in the `velocity.h5` file so the first dataset is no longer velocity. The present implementation of `asc_desc2horz_vert.py` does not check the name of the dataset it is reading and it provides no way to use a component other than the first dataset.

**Full script that generated the error**

```
asc_desc2horz_vert.py A135_geo_velocity_v6a_subset.h5 D098_geo_velocity_v3a_subset.h5
```

**Full error message**

```
Using default MintPy Path: /home/fielding/tools/MintPy
---------------------
reading A135_geo_velocity_v6a_subset.h5
reading D098_geo_velocity_v3a_subset.h5
---------------------
get design matrix
incidence angle: 38.95743031204843
heading angle: 349.125244140625
incidence angle: 33.72858887716663
heading angle: 192.2511058816865
project asc/desc into horz/vert direction
---------------------
writing horizontal component to file: hz.h5
create HDF5 file: hz.h5 with w mode
create dataset /velocity of float32    in size of (614, 1072)          with compression=None
finished writing to hz.h5
writing   vertical component to file: up.h5
create HDF5 file: up.h5 with w mode
create dataset /velocity of float32    in size of (614, 1072)          with compression=None
finished writing to up.h5

```

but the input file has many datasets:
```
info.py D098_geo_velocity_v3a_subset.h5
...
HDF5 dataset "/step20200107        ": shape (614, 1072)         , dtype <float32>
HDF5 dataset "/step20200107Std     ": shape (614, 1072)         , dtype <float32>
HDF5 dataset "/step20200502        ": shape (614, 1072)         , dtype <float32>
HDF5 dataset "/step20200502Std     ": shape (614, 1072)         , dtype <float32>
HDF5 dataset "/step20200703        ": shape (614, 1072)         , dtype <float32>
HDF5 dataset "/step20200703Std     ": shape (614, 1072)         , dtype <float32>
HDF5 dataset "/velocity            ": shape (614, 1072)         , dtype <float32>
HDF5 dataset "/velocityStd         ": shape (614, 1072)         , dtype <float32>
```

I guess I could make four copies of the `velocity.h5` file and then remove all the datasets but the one I want to use in the  `asc_desc2horz_vert` program, but that seems like a painful workaround.

**System information**

* Operating system: Linux-CentOS
* Python environment: conda
* Version of MintPy:  Using default MintPy Path: /home/fielding/tools/MintPy
MintPy release version v1.2.3-49, release date 2020-10-01
* Your custom / default template file (if the bug is related to a specific dataset):

### PR DESCRIPTION
**Pull request by yunjunz**
**Description of proposed changes**

asc_desc2horz_vert: add --dset option to be able to customize the dataset to read/use to asc/desc 2 horz/vert conversion, for input file with more than one dataset.

**Reminders**

- [x] Fix #456
- [x] Pass Codacy code review (green)
- [x] Pass Circle CI test (green)
- [x] If adding new functionality, add a detailed description to the documentation and/or an example.

### CODE REVIEW

**Comment by EJFielding** [comment]
This works great! Thanks @yunjunz. Here are two maps made from the 5th component in my `velocity.h5` file (step functions for an earthquake on July 3, 2020):
up-step20200703

East-step20200703

**Comment by yunjunz** [comment]
Hi @EJFielding, masking with maskTempCoh.h5 is automatically searched and applied to velocity.h5 in view.py, the velocity.h5 is not really masked on the disk, unless you run mask.py on it.

**Comment by EJFielding** [comment]
Thanks. I think I learned about that masking situation back in February when I was doing this calculation on the step function for the January earthquake, but I forgot.

**Comment by EJFielding** [comment]
The great thing about the vertical and horizontal conversion is that it makes easier to see that there are probably two different earthquake signals in the 20200703 step change along the coast, one southeast of the reference point and a different one southwest.

**Comment by yunjunz** [comment]
I was wondering about the signal on the SW of the reference point, seems very interesting!

**Pull request merged**
